name: "Project"

pandoc_path: "/usr/lib/rstudio-server/bin/quarto/bin/tools"
threads: 15
# Whether zip archive with results should be created
# TODO
create_archive: "yes"
# should the html output be self contained or have a separate lib directory
# separate lib directory saves space, but individual html files can't be shared
self_contained: FALSE

# Unique strings that are recognized as section headings in the IPA text report
parse_strings:
  canonical: "Canonical Pathways for"
  upstream: "Upstream Regulators"
  disease: "Diseases and Bio Functions"
  tox: "Tox Functions"
  regulator: "Regulator Effects"
  networks: "Networks"
  molecules: ""

# Options for graphs
canonical:
  graph_nitems: 20
upstream:
  graph_pval_threshold: 0.05
  graph_zscore_threshold: 1
disease:
  graph_pval_threshold: 0.05
  graph_zscore_threshold: 1
