---
title: "IPA analysis"
author: "icervenka"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(dplyr)
```

### Canonical Pathways

```{r canonical_graph, echo=FALSE, out.width = "100%"}
canonical_graph
```

```{r canonical_table, echo=FALSE}
display_df = canonical_df %>% filter(`-log10(pvalue)` > 1.3) %>% select(c(1:5))
columns_opts = list(list(width = '2%'), list(width = '20%'), list(width = '2%'), list(width = '2%'), list(width = '2%'), list(width = '40%'))
DT::datatable(display_df, options = list(autoWidth = FALSE, columns = columns_opts), caption="IPA Canonical pathways")
```

### Upstream regulators

```{r upstream_graph, echo=FALSE, out.width = "100%"}
upstream_graph
```

```{r upstream_table, echo=FALSE}
display_df = upstream_df %>% select(c(-1, -7))
columns_defs = list(list(width = '30%', target = 10))
DT::datatable(display_df, options = list(autoWidth = FALSE, columnDefs = columns_defs), caption="IPA Upstream regulators")
```

### Disese and functions

```{r disease_graph, echo=FALSE, out.width = "100%"}
disease_graph
```

```{r disease_table, echo=FALSE}
display_df = disease_df %>% select(c(-2))
columns_defs = list(list(width = '30%', target = 2))
DT::datatable(display_df, options = list(autoWidth = FALSE, columnDefs = columns_defs), caption="IPA Diseases and Functions")
```
